// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbpLi5i3AGTQJG15qvDPGPRmJEFCtQ5sE',
    appId: '1:4807271729:web:9f52605fe41c77a0793c10',
    messagingSenderId: '4807271729',
    projectId: 'fasum-app-67b3d',
    authDomain: 'fasum-app-67b3d.firebaseapp.com',
    storageBucket: 'fasum-app-67b3d.appspot.com',
    measurementId: 'G-LSJY95B85J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvup7mKIPmL7AyQafNkTLQ8r0LdcxqYQg',
    appId: '1:4807271729:android:29548a07eb0edebb793c10',
    messagingSenderId: '4807271729',
    projectId: 'fasum-app-67b3d',
    storageBucket: 'fasum-app-67b3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsoBUdSt9wWugBmQmGEHxCM1fX4UlUE-A',
    appId: '1:4807271729:ios:a39cbe9e6c7c430d793c10',
    messagingSenderId: '4807271729',
    projectId: 'fasum-app-67b3d',
    storageBucket: 'fasum-app-67b3d.appspot.com',
    iosBundleId: 'com.example.tugasderylPostscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsoBUdSt9wWugBmQmGEHxCM1fX4UlUE-A',
    appId: '1:4807271729:ios:a39cbe9e6c7c430d793c10',
    messagingSenderId: '4807271729',
    projectId: 'fasum-app-67b3d',
    storageBucket: 'fasum-app-67b3d.appspot.com',
    iosBundleId: 'com.example.tugasderylPostscreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbpLi5i3AGTQJG15qvDPGPRmJEFCtQ5sE',
    appId: '1:4807271729:web:9bf132d11f2f3e47793c10',
    messagingSenderId: '4807271729',
    projectId: 'fasum-app-67b3d',
    authDomain: 'fasum-app-67b3d.firebaseapp.com',
    storageBucket: 'fasum-app-67b3d.appspot.com',
    measurementId: 'G-WC6WJEZT6L',
  );

}